### ISSUE TITLE
Error: "This document is too large to continue editing"

### ISSUE THREAD

**Issue by miketaylr** [mozilla/tsci#75]
This happened over the weekend -- I think on the very last week for my `npm start 2018` run:

```
Added sheet with ID 1333570091
Inserted header row
(node:89117) UnhandledPromiseRejectionWarning: Error: This document is too large to continue editing.
    at Gaxios.<anonymous> (/Users/miket/dev/tsci/node_modules/gaxios/build/src/gaxios.js:73:27)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/miket/dev/tsci/node_modules/gaxios/build/src/gaxios.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:89117) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

```

**Comment by miketaylr** [comment]
https://github.com/googleapis/gaxios is a Google thing... so this might just be a bug in the googleapis package.

**Comment by past** [comment]
This is just a rejected promise that we didn't explicitly handle. The error message seems too severe to handle anyway. Do you get the same error if you manually try to add a new sheet to that document?

**Comment by past** [comment]
[This](https://stackoverflow.com/questions/52880742/google-sheet-api-isnt-updating-for-document-too-large) suggests that removing version history will help.

**Comment by miketaylr** [comment]
Just ran into this again, after 26 hours (got me from Jan 06, 2019 to May 19, 2019). It seems like the spreadsheet fails to save an update manually (adding "hello" to a cell).

I guess this is something we need to tackle before we can just run this thing on cron and expect it to not blow up. Seems reasonable to only keep a few history revisions, and just delete anything older as we add new ones.

**Comment by miketaylr** [comment]
We could also only react if we hit this error.

https://developers.google.com/sheets/api/reference/rest/v4/ErrorCode

> DOCUMENT_TOO_LARGE_TO_EDIT | Indicates that a document is too large to continue editing. Making a copy of the spreadsheet may fix the issue.

**Comment by past** [comment]
Have you got this error when starting from a new spreadsheet or just when starting with an existing one (presumably with a number of edits) and appending to it?

If it's the former, we really need to handle the error by pausing, copying the current spreadsheet to a new one and continuing there. If it's the latter, an easier approach would be to just start from a clone immediately (when `spreadsheetId` is specified) in order to not hit that error.

**Comment by miketaylr** [comment]
> Have you got this error when starting from a new spreadsheet

Oof, I can't remember 100%. I believe I started a new spreadsheet, let it run for 1 week, added a Summary sheet, then pasted the ID into the config and let it run for the rest of the dates.

**Comment by miketaylr** [comment]
Just realized we hit this so fast because it's probably creating a history entry per row insertion.

**Comment by hackhnaton1994** [comment]
Waiting

**Comment by hackhnaton1994** [comment]
Umbrella Popularity List
The popularity list contains our most queried domains based on passive DNS usage across our Umbrella global network of more than 100 Billion requests per day with 65 million unique active users, in more than 165 countries. Unlike Alexa, the metric is not based on only browser based 'http' requests from users but rather takes in to account the number of unique client IPs invoking this domain relative to the sum of all requests to all domains. In other words, our popularity ranking reflects the domain’s relative internet activity agnostic to the invocation protocols and applications where as ’site ranking’ models (such as Alexa) focus on the web activity over port 80 mainly from browsers.

As for Alexa, the site’s rank is based on combined measure of unique visitors (Alexa users who visit the site per day) and page views (total URL requests from Alexa users for a site). Umbrella popularity lists are generated on a daily basis reflecting the actual world-wide usage of domains by Umbrella global network users and includes root domains, subdomains in addition to TLDs (Alexa list has only this). In addition, Umbrella popularity algorithm also applies data normalization methodologies to smoothen potential biases that may occur in the data due to sampling of the DNS usage data.

Top 1 million
http://s3-us-west-1.amazonaws.com/umbrella-static/top-1m.csv.zip

Top TLDs
http://s3-us-west-1.amazonaws.com/umbrella-static/top-1m-TLD.csv.zip

Historical

**Comment by hackhnaton1994** [comment]
If havs anny issue give me link

**Comment by miketaylr** [comment]
I think it's safe to close this one again.
